### ISSUE TITLE
How to update?

### ISSUE THREAD

**Issue by diskmanti** [kirqe/autm-rb#6]
Hello,

I am a proud user of this theme and I wanted to tell you it is one of the best I have seen. It is minimal and cool at the same time. So congratulation and keep up the good work. 😄 

I wante to ask you how can I update my blog to use the current version of you theme. I usually make a backup of the entire blog, delete the old repo, refork your repo and reupload the settings file and blog files. I know there is a simpler way and I would appreciate if you could help me.

Thanks in advance and Cheers!! 🍻 😄

**Comment by kirqe** [comment]
Hi, thanks :) 

I think this is what you're looking for  http://stackoverflow.com/questions/7244321/how-do-i-update-a-github-forked-repository

**Comment by diskmanti** [comment]
Hello,

Thanks for the feedback. 😄
